cf_method: our # dice, cchvae, gs, face
cfs_num: 5 # desired number of counterfactuals, i.e. k
data_name: loan # adult, loan, give_me_some_credit, compas
eva_frac: 0.75 # fix
feat_num: 4 # desired number of changed features, i.e. p
inference_frac: 1 # fix
instance_num: 10 # number of tested instances: 1000 for adult; 100 for compas; 300 for credit; 10 for loan
privacy: true # true is to test privacy; false is to test counterfactual quality 
